services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev  # Use this for Vite in development

  sanity:
    build:
      context: ./cms
    ports:
      - "3333:3333"
    volumes:
      - ./cms:/app
      - /app/node_modules
    environment:
      - SANITY_STUDIO_PROJECT_ID=or9vpa2z
      - SANITY_STUDIO_DATASET=production
      - NODE_ENV=development
    command: npx sanity dev  # Correct command to run Sanity Studio in development
